// ── Traffic Dashboard — chart rendering, metrics, and time range controls ──
// This file is referenced by the HTML generated by Generate-TrafficDashboard-Premium-v2.ps1.
// The HTML injects allData/refData/pathData inline then calls initDashboard().

/* exported initDashboard */

// ── Custom tooltip (dark card with colored dots) ──
const tooltipPlugin = {
  enabled: false,
  external: function(context) {
    let el = document.getElementById('chartjs-tooltip');
    if (!el) {
      el = document.createElement('div');
      el.id = 'chartjs-tooltip';
      el.style.cssText = 'position:absolute;pointer-events:none;background:#1a1a1e;border:1px solid rgba(255,255,255,0.12);border-radius:10px;padding:10px 14px;font-family:Inter,system-ui,sans-serif;font-size:12px;color:#ededed;z-index:200;box-shadow:0 8px 24px rgba(0,0,0,0.6);transition:opacity 0.15s ease;min-width:140px';
      document.body.appendChild(el);
    }
    const tooltip = context.tooltip;
    if (tooltip.opacity === 0) { el.style.opacity = '0'; return; }

    let html = '<div style="font-weight:600;margin-bottom:6px;color:#aaa">' + tooltip.title[0] + '</div>';
    tooltip.body.forEach(function(item, i) {
      const colors = tooltip.labelColors[i];
      const dot = '<span style="display:inline-block;width:8px;height:8px;border-radius:50%;background:' + colors.borderColor + ';margin-right:8px"></span>';
      const parts = item.lines[0].split(': ');
      const label = parts[0];
      const value = parts[1] || parts[0];
      html += '<div style="display:flex;justify-content:space-between;align-items:center;gap:16px;padding:2px 0">'
        + '<span>' + dot + label + '</span>'
        + '<span style="font-weight:700;font-variant-numeric:tabular-nums">' + (parts.length > 1 ? value : '') + '</span>'
        + '</div>';
    });
    el.innerHTML = html;
    el.style.opacity = '1';
    const pos = context.chart.canvas.getBoundingClientRect();
    el.style.left = pos.left + window.scrollX + tooltip.caretX + 'px';
    el.style.top = pos.top + window.scrollY + tooltip.caretY - 10 + 'px';
    var rect = el.getBoundingClientRect();
    if (rect.right > window.innerWidth - 10) {
      el.style.left = (pos.left + window.scrollX + tooltip.caretX - rect.width - 12) + 'px';
    }
  }
};

// ── Chart defaults and helpers ──
Chart.defaults.color = '#555';
Chart.defaults.font.family = 'Inter, system-ui, sans-serif';
Chart.defaults.font.size = 12;
Chart.defaults.elements.point.radius = 0;
Chart.defaults.elements.point.hoverRadius = 5;
Chart.defaults.elements.line.borderWidth = 2;

var gY = { grid: { color: 'rgba(255,255,255,0.04)', drawBorder: false }, beginAtZero: true };
var gX = { grid: { display: false } };

function grad(ctx, r, g, b, h) {
  var gr = ctx.createLinearGradient(0, 0, 0, h || 240);
  gr.addColorStop(0, 'rgba(' + r + ',' + g + ',' + b + ',0.18)');
  gr.addColorStop(1, 'rgba(' + r + ',' + g + ',' + b + ',0)');
  return gr;
}

var legendOpts = { position: 'bottom', align: 'center', labels: { usePointStyle: true, pointStyle: 'circle', boxWidth: 6, padding: 16, font: { size: 12 } } };
function lineOpts(legend) {
  return {
    responsive: true,
    interaction: { intersect: false, mode: 'index' },
    plugins: { legend: legend ? legendOpts : { display: false }, tooltip: tooltipPlugin },
    scales: { y: gY, x: gX }
  };
}

// Layout constant — shared across all charts that show release annotations
var RELEASE_LABEL_PADDING = 56;

// ── Shared release annotation plugin builder ──
// Returns a Chart.js plugin that draws vertical dashed lines at release dates.
// Staggers labels vertically when releases are too close together to avoid overlap.
function makeReleasePlugin(releases, filteredDatesRef) {
  return {
    id: 'releaseLines',
    afterDraw: function(chart) {
      if (!releases || !releases.length) return;
      var dates = filteredDatesRef();
      var visible = releases
        .filter(function(r) { return dates.indexOf(r.date) !== -1; })
        .map(function(r) { return { version: r.version, date: r.date, idx: dates.indexOf(r.date) }; })
        .sort(function(a, b) { return a.idx - b.idx; });
      if (!visible.length) return;
      // Deduplicate: keep only the highest version per chart date
      var deduped = {};
      visible.forEach(function(r) {
        var key = r.idx;
        if (!(key in deduped)) {
          deduped[key] = r;
        } else {
          var cur = deduped[key].version.replace(/^v/, '').split('.').map(Number);
          var cand = r.version.replace(/^v/, '').split('.').map(Number);
          for (var i = 0; i < 3; i++) {
            if ((cand[i] || 0) > (cur[i] || 0)) { deduped[key] = r; break; }
            if ((cand[i] || 0) < (cur[i] || 0)) break;
          }
        }
      });
      visible = Object.keys(deduped).map(function(k) { return deduped[k]; })
        .sort(function(a, b) { return a.idx - b.idx; });
      var ctx = chart.ctx;
      var xAxis = chart.scales.x;
      var yAxis = chart.scales.y;
      ctx.save();
      ctx.font = '10px Inter, sans-serif';
      // Measure label widths and assign stagger tiers to avoid overlap
      var minGap = 8; // px padding between labels
      var tierSpacing = 14; // vertical px between stagger tiers
      var topPad = (chart.options.layout && chart.options.layout.padding) ? chart.options.layout.padding.top : RELEASE_LABEL_PADDING;
      var maxTiers = Math.max(1, Math.floor(topPad / tierSpacing));
      var placed = []; // {left, right, tier}
      visible.forEach(function(r) {
        var x = xAxis.getPixelForValue(r.idx);
        var w = ctx.measureText(r.version).width;
        var left = x - w / 2;
        var right = x + w / 2;
        // Find lowest tier that doesn't collide, clamped to maxTiers
        var tier = 0;
        var foundTier = false;
        for (var t = 0; t < maxTiers; t++) {
          var collision = false;
          for (var p = 0; p < placed.length; p++) {
            if (placed[p].tier === t && !(right + minGap < placed[p].left || left - minGap > placed[p].right)) {
              collision = true;
              break;
            }
          }
          if (!collision) { tier = t; foundTier = true; break; }
        }
        if (!foundTier) { tier = maxTiers - 1; }
        placed.push({ left: left, right: right, tier: tier });
        r.x = x;
        r.tier = tier;
      });
      // Draw lines and labels (font already set above)
      ctx.fillStyle = 'rgba(255,255,255,0.7)';
      ctx.textAlign = 'center';
      visible.forEach(function(r) {
        ctx.beginPath();
        ctx.setLineDash([4, 4]);
        ctx.strokeStyle = 'rgba(255,255,255,0.35)';
        ctx.lineWidth = 1;
        ctx.moveTo(r.x, yAxis.top);
        ctx.lineTo(r.x, yAxis.bottom);
        ctx.stroke();
        ctx.setLineDash([]);
        ctx.fillText(r.version, r.x, yAxis.top - 6 - (r.tier * tierSpacing));
      });
      ctx.restore();
    }
  };
}

// ── Chart instances ──
var viewsChart, clonesChart, starsChart, psGalleryChart;
var showReleases = true;
var currentDays = 0;

function buildCharts(allData, days) {
  currentDays = days;
  function filterByDays(dates) {
    var arrays = Array.prototype.slice.call(arguments, 1);
    if (!days || days === 0) { return { dates: dates, arrays: arrays }; }
    if (!dates.length) { return { dates: [], arrays: arrays.map(function() { return []; }) }; }
    var anchor = new Date(dates[dates.length - 1] + 'T12:00:00');
    var t = new Date(anchor);
    t.setDate(t.getDate() - days);
    var cutoff = t.getFullYear() + '-' +
      String(t.getMonth() + 1).padStart(2, '0') + '-' +
      String(t.getDate()).padStart(2, '0');
    var filtered = { dates: [], arrays: arrays.map(function() { return []; }) };
    dates.forEach(function(d, i) {
      if (d > cutoff) {
        filtered.dates.push(d);
        arrays.forEach(function(arr, j) { filtered.arrays[j].push(arr[i]); });
      }
    });
    return filtered;
  }

  [viewsChart, clonesChart, starsChart, psGalleryChart].forEach(function(ch) { if (ch) { ch.destroy(); } });

  // Views
  var v = filterByDays(allData.views.dates, allData.views.total, allData.views.unique);
  var vc = document.getElementById('viewsChart').getContext('2d');
  var viewsOpts = lineOpts(true);
  viewsOpts.layout = { padding: { top: RELEASE_LABEL_PADDING } };
  viewsChart = new Chart(vc, {
    type: 'line',
    data: {
      labels: v.dates,
      datasets: [
        { label: 'Total', data: v.arrays[0], borderColor: '#3b82f6', backgroundColor: grad(vc, 59, 130, 246), fill: true, tension: 0.4 },
        { label: 'Unique', data: v.arrays[1], borderColor: '#22c55e', backgroundColor: grad(vc, 34, 197, 94), fill: true, tension: 0.4 }
      ]
    },
    options: viewsOpts,
    plugins: showReleases ? [makeReleasePlugin(allData.releases, function() { return v.dates; })] : []
  });
  var viewsSum = v.arrays[0].reduce(function(a, b) { return a + b; }, 0);
  document.getElementById('viewsStat').textContent = viewsSum.toLocaleString();

  // Clones
  var cl = filterByDays(allData.clones.dates, allData.clones.total, allData.clones.unique);
  var cc = document.getElementById('clonesChart').getContext('2d');
  var clonesOpts = lineOpts(true);
  clonesOpts.layout = { padding: { top: RELEASE_LABEL_PADDING } };
  clonesChart = new Chart(cc, {
    type: 'line',
    data: {
      labels: cl.dates,
      datasets: [
        { label: 'Total', data: cl.arrays[0], borderColor: '#a855f7', backgroundColor: grad(cc, 168, 85, 247), fill: true, tension: 0.4 },
        { label: 'Unique', data: cl.arrays[1], borderColor: '#f43f5e', backgroundColor: grad(cc, 244, 63, 94), fill: true, tension: 0.4 }
      ]
    },
    options: clonesOpts,
    plugins: showReleases ? [makeReleasePlugin(allData.releases, function() { return cl.dates; })] : []
  });
  var clonesSum = cl.arrays[0].reduce(function(a, b) { return a + b; }, 0);
  document.getElementById('clonesStat').textContent = clonesSum.toLocaleString();

  // Stars
  var st = filterByDays(allData.stars.dates, allData.stars.cumulative);
  var sc = document.getElementById('starsChart').getContext('2d');
  var filteredUsers = allData.stars.users.slice(allData.stars.dates.length - st.dates.length);
  starsChart = new Chart(sc, {
    type: 'line',
    data: {
      labels: st.dates,
      datasets: [{
        data: st.arrays[0],
        borderColor: '#f59e0b',
        backgroundColor: grad(sc, 245, 158, 11),
        fill: true, tension: 0.4,
        pointRadius: 4, pointBackgroundColor: '#f59e0b', pointBorderColor: '#050507', pointBorderWidth: 2
      }]
    },
    options: {
      responsive: true,
      interaction: { intersect: false, mode: 'index' },
      plugins: {
        legend: { display: false },
        tooltip: {
          enabled: false,
          external: function(context) {
            var el = document.getElementById('chartjs-tooltip');
            if (!el) {
              el = document.createElement('div');
              el.id = 'chartjs-tooltip';
              el.style.cssText = 'position:absolute;pointer-events:none;background:#1a1a1e;border:1px solid rgba(255,255,255,0.12);border-radius:10px;padding:10px 14px;font-family:Inter,system-ui,sans-serif;font-size:12px;color:#ededed;z-index:200;box-shadow:0 8px 24px rgba(0,0,0,0.6);transition:opacity 0.15s ease';
              document.body.appendChild(el);
            }
            var tt = context.tooltip;
            if (tt.opacity === 0) { el.style.opacity = '0'; return; }
            var idx = tt.dataPoints && tt.dataPoints[0] ? tt.dataPoints[0].dataIndex : 0;
            var user = filteredUsers[idx] || '';
            el.innerHTML = '<div style="font-weight:600;margin-bottom:4px;color:#aaa">' + tt.title[0] + '</div>'
              + '<div style="display:flex;justify-content:space-between;gap:16px"><span><span style="display:inline-block;width:8px;height:8px;border-radius:50%;background:#f59e0b;margin-right:8px"></span>Star #' + tt.dataPoints[0].raw + '</span><span style="font-weight:700">' + user + '</span></div>';
            el.style.opacity = '1';
            var pos = context.chart.canvas.getBoundingClientRect();
            el.style.left = pos.left + window.scrollX + tt.caretX + 'px';
            el.style.top = pos.top + window.scrollY + tt.caretY - 10 + 'px';
          }
        }
      },
      scales: { y: gY, x: gX },
      layout: { padding: { top: RELEASE_LABEL_PADDING } }
    },
    plugins: showReleases ? [makeReleasePlugin(allData.releases, function() { return st.dates; })] : []
  });
  if (st.arrays[0].length > 0) {
    document.getElementById('starsStat').textContent = st.arrays[0][st.arrays[0].length - 1];
  }

  // PSGallery Downloads (cumulative) with release annotations
  var pgEl = document.getElementById('psGalleryChart');
  if (pgEl && allData.psGallery && allData.psGallery.dates.length > 0) {
    var pg = filterByDays(allData.psGallery.dates, allData.psGallery.totalDl);
    var pgc = pgEl.getContext('2d');

    var pgOpts = lineOpts(false);
    pgOpts.layout = { padding: { top: RELEASE_LABEL_PADDING } };

    psGalleryChart = new Chart(pgc, {
      type: 'line',
      data: {
        labels: pg.dates,
        datasets: [{
          label: 'Total Downloads',
          data: pg.arrays[0],
          borderColor: '#06b6d4',
          backgroundColor: grad(pgc, 6, 182, 212),
          fill: true, tension: 0.4
        }]
      },
      options: pgOpts,
      plugins: showReleases ? [makeReleasePlugin(allData.releases, function() { return pg.dates; })] : []
    });
    if (pg.arrays[0].length > 0) {
      document.getElementById('psGalleryStat').textContent = pg.arrays[0][pg.arrays[0].length - 1].toLocaleString();
    }
  }
}

// ── Update header metrics + insights for selected time range ──
function updateMetrics(allData, days) {
  var rangeLabel = days === 0 ? 'All Time' : days + 'd';

  function windowData(src, valKey, uniqKey, windowDays) {
    if (!windowDays || windowDays === 0) {
      return { dates: src.dates, values: src[valKey], uniques: src[uniqKey] };
    }
    if (!src.dates.length) { return { dates: [], values: [], uniques: [] }; }
    var anchor = new Date(src.dates[src.dates.length - 1] + 'T12:00:00');
    var t = new Date(anchor); t.setDate(t.getDate() - windowDays);
    var cutoff = t.getFullYear() + '-' + String(t.getMonth() + 1).padStart(2, '0') + '-' + String(t.getDate()).padStart(2, '0');
    var r = { dates: [], values: [], uniques: [] };
    src.dates.forEach(function(d, i) {
      if (d > cutoff) { r.dates.push(d); r.values.push(src[valKey][i]); r.uniques.push(src[uniqKey][i]); }
    });
    return r;
  }

  function rollingDelta(src, valKey, windowDays) {
    if (!windowDays || windowDays === 0) { return { current: 0, prior: 0, delta: 0, hasData: false }; }
    if (!src.dates.length) { return { current: 0, prior: 0, delta: 0, hasData: false }; }
    var anchor = new Date(src.dates[src.dates.length - 1] + 'T12:00:00');
    var t = new Date(anchor); t.setDate(t.getDate() - windowDays);
    var cutoff = t.getFullYear() + '-' + String(t.getMonth() + 1).padStart(2, '0') + '-' + String(t.getDate()).padStart(2, '0');
    var t2 = new Date(anchor); t2.setDate(t2.getDate() - windowDays * 2);
    var priorCutoff = t2.getFullYear() + '-' + String(t2.getMonth() + 1).padStart(2, '0') + '-' + String(t2.getDate()).padStart(2, '0');
    var current = 0, prior = 0;
    src.dates.forEach(function(d, i) {
      if (d > cutoff) { current += src[valKey][i]; }
      else if (d > priorCutoff && d <= cutoff) { prior += src[valKey][i]; }
    });
    var delta = prior > 0 ? Math.round((current - prior) / prior * 100) : 0;
    return { current: current, prior: prior, delta: delta, hasData: prior > 0 };
  }

  var vw = windowData(allData.views, 'total', 'unique', days);
  var cw = windowData(allData.clones, 'total', 'unique', days);

  var viewsTotal = vw.values.reduce(function(a, b) { return a + b; }, 0);
  var viewsUnique = vw.uniques.reduce(function(a, b) { return a + b; }, 0);
  var clonesTotal = cw.values.reduce(function(a, b) { return a + b; }, 0);
  var clonesUnique = cw.uniques.reduce(function(a, b) { return a + b; }, 0);

  var allTimeViews = allData.views.total.reduce(function(a, b) { return a + b; }, 0);
  var allTimeClones = allData.clones.total.reduce(function(a, b) { return a + b; }, 0);

  var compareWindow = days === 0 ? 7 : days;
  var vDelta = rollingDelta(allData.views, 'total', compareWindow);
  var cDelta = rollingDelta(allData.clones, 'total', compareWindow);
  var compareLabel = days === 0 ? 'WoW' : 'vs prior';

  var vCls = vDelta.hasData ? (vDelta.delta > 0 ? 'up' : vDelta.delta < 0 ? 'down' : 'flat') : 'flat';
  var vArrow = vDelta.delta > 0 ? '\u2191' : vDelta.delta < 0 ? '\u2193' : '\u2192';
  document.getElementById('hdr-views-label').textContent = 'Views (' + rangeLabel + ')';
  document.getElementById('hdr-views-value').textContent = viewsTotal.toLocaleString();
  document.getElementById('hdr-views-sub').innerHTML = viewsUnique.toLocaleString() + ' unique &middot; ' + allTimeViews.toLocaleString() + ' all-time';
  var vDeltaEl = document.getElementById('hdr-views-delta');
  vDeltaEl.className = 'm-delta ' + vCls;
  vDeltaEl.textContent = vDelta.hasData ? (vArrow + ' ' + vDelta.delta + '% ' + compareLabel) : '\u2014 N/A';

  var cCls = cDelta.hasData ? (cDelta.delta > 0 ? 'up' : cDelta.delta < 0 ? 'down' : 'flat') : 'flat';
  var cArrow = cDelta.delta > 0 ? '\u2191' : cDelta.delta < 0 ? '\u2193' : '\u2192';
  document.getElementById('hdr-clones-label').textContent = 'Clones (' + rangeLabel + ')';
  document.getElementById('hdr-clones-value').textContent = clonesTotal.toLocaleString();
  document.getElementById('hdr-clones-sub').innerHTML = clonesUnique.toLocaleString() + ' unique &middot; ' + allTimeClones.toLocaleString() + ' all-time';
  var cDeltaEl = document.getElementById('hdr-clones-delta');
  cDeltaEl.className = 'm-delta ' + cCls;
  cDeltaEl.textContent = cDelta.hasData ? (cArrow + ' ' + cDelta.delta + '% ' + compareLabel) : '\u2014 N/A';

  // Insight cards
  var cloneRate = viewsTotal > 0 ? (clonesTotal / viewsTotal * 100).toFixed(1) : '0';
  document.getElementById('ins-clone-rate').textContent = cloneRate + '%';
  document.getElementById('ins-clone-rate-sub').textContent = clonesTotal.toLocaleString() + ' clones / ' + viewsTotal.toLocaleString() + ' views';

  var numDays = vw.dates.length || 1;
  document.getElementById('ins-avg-views').textContent = Math.round(viewsTotal / numDays).toLocaleString();
  document.getElementById('ins-avg-views-sub').textContent = numDays + ' days in window';

  var peakVal = 0, peakDate = '';
  vw.values.forEach(function(v, i) { if (v > peakVal) { peakVal = v; peakDate = vw.dates[i]; } });
  document.getElementById('ins-peak-day').textContent = peakVal.toLocaleString();
  document.getElementById('ins-peak-sub').textContent = peakDate || '\u2014';

  if (allData.stars.dates.length > 0) {
    var lastStar = allData.stars.dates[allData.stars.dates.length - 1];
    var lastStarLocal = new Date(lastStar + 'T12:00:00');
    var diff = Math.floor((new Date() - lastStarLocal) / 86400000);
    document.getElementById('ins-star-gap').textContent = diff;
    document.getElementById('ins-star-gap-sub').textContent = 'last: ' + allData.stars.users[allData.stars.users.length - 1] + ' on ' + lastStar;
  } else {
    document.getElementById('ins-star-gap').textContent = '\u2014';
    document.getElementById('ins-star-gap-sub').textContent = 'no stars yet';
  }

  buildWeeklyTrend(allData, vw);
}

function buildWeeklyTrend(allData, windowedViews) {
  // Week = Sunday through Saturday
  function toWeekKey(dateStr) {
    var d = new Date(dateStr + 'T12:00:00');
    var day = d.getDay(); // 0=Sun, 6=Sat
    var sun = new Date(d); sun.setDate(d.getDate() - day); // back to Sunday
    return sun.getFullYear() + '-' + String(sun.getMonth() + 1).padStart(2, '0') + '-' + String(sun.getDate()).padStart(2, '0');
  }

  // Build weeks from FULL dataset so every week has complete 7-day totals
  var weeks = {};
  allData.views.dates.forEach(function(d, i) {
    var wk = toWeekKey(d);
    if (!weeks[wk]) { weeks[wk] = { views: 0, clones: 0 }; }
    weeks[wk].views += allData.views.total[i];
  });
  allData.clones.dates.forEach(function(d, i) {
    var wk = toWeekKey(d);
    if (!weeks[wk]) { weeks[wk] = { views: 0, clones: 0 }; }
    weeks[wk].clones += allData.clones.total[i];
  });

  // Determine which weeks overlap with the selected window
  var windowDates = {};
  windowedViews.dates.forEach(function(d) { windowDates[toWeekKey(d)] = true; });

  var sortedWeeks = Object.keys(weeks).sort().filter(function(wk) {
    return windowDates[wk];
  });
  var tbody = document.getElementById('trend-table-body');
  var html = '';

  sortedWeeks.forEach(function(wk, idx) {
    var w = weeks[wk];
    var sun = new Date(wk + 'T12:00:00');
    var sat = new Date(sun); sat.setDate(sun.getDate() + 6);
    var wkLabel = (sun.getMonth() + 1) + '/' + sun.getDate() + ' \u2013 ' + (sat.getMonth() + 1) + '/' + sat.getDate();

    var vDelta = '', cDelta = '';
    if (idx > 0) {
      var prev = weeks[sortedWeeks[idx - 1]];
      if (prev.views > 0) {
        var pct = Math.round((w.views - prev.views) / prev.views * 100);
        var cls = pct > 0 ? 'td-up' : pct < 0 ? 'td-down' : 'td-flat';
        vDelta = '<span class="' + cls + '">' + (pct > 0 ? '\u2191' : pct < 0 ? '\u2193' : '\u2192') + ' ' + pct + '%</span>';
      } else {
        vDelta = '<span class="td-flat">\u2014</span>';
      }
      if (prev.clones > 0) {
        var pct2 = Math.round((w.clones - prev.clones) / prev.clones * 100);
        var cls2 = pct2 > 0 ? 'td-up' : pct2 < 0 ? 'td-down' : 'td-flat';
        cDelta = '<span class="' + cls2 + '">' + (pct2 > 0 ? '\u2191' : pct2 < 0 ? '\u2193' : '\u2192') + ' ' + pct2 + '%</span>';
      } else {
        cDelta = '<span class="td-flat">\u2014</span>';
      }
    } else {
      vDelta = '<span class="td-flat">\u2014</span>';
      cDelta = '<span class="td-flat">\u2014</span>';
    }

    var rate = w.views > 0 ? (w.clones / w.views * 100).toFixed(1) + '%' : '\u2014';
    html += '<tr><td>' + wkLabel + '</td><td class="td-value">' + w.views.toLocaleString() + '</td><td>' + vDelta + '</td><td class="td-value">' + w.clones.toLocaleString() + '</td><td>' + cDelta + '</td><td>' + rate + '</td></tr>';
  });

  tbody.innerHTML = html;
}

// ── Time range menu ──
function toggleMenu() {
  document.getElementById('rangeMenu').classList.toggle('open');
}
document.addEventListener('click', function(e) {
  if (!e.target.closest('.range-picker')) {
    document.getElementById('rangeMenu').classList.remove('open');
  }
});

// ── Main entry point — called by inline script after data injection ──
function initDashboard(allData, refData, pathData) {
  // Static charts (referrers + paths — not time-filtered)
  new Chart(document.getElementById('referrersChart'), {
    type: 'bar',
    data: {
      labels: refData.labels,
      datasets: [
        { label: 'Views', data: refData.views, backgroundColor: 'rgba(59,130,246,0.5)', borderRadius: 4, borderSkipped: false },
        { label: 'Unique', data: refData.uniques, backgroundColor: 'rgba(34,197,94,0.4)', borderRadius: 4, borderSkipped: false }
      ]
    },
    options: { responsive: true, indexAxis: 'y',
      plugins: { legend: legendOpts, tooltip: tooltipPlugin },
      scales: { x: Object.assign({}, gY), y: gX } }
  });

  new Chart(document.getElementById('pathsChart'), {
    type: 'bar',
    data: {
      labels: pathData.labels,
      datasets: [{
        label: 'Views', data: pathData.views,
        backgroundColor: ['rgba(59,130,246,0.45)', 'rgba(168,85,247,0.45)', 'rgba(34,197,94,0.45)', 'rgba(244,63,94,0.45)', 'rgba(245,158,11,0.45)', 'rgba(6,182,212,0.45)', 'rgba(236,72,153,0.45)', 'rgba(132,204,22,0.45)', 'rgba(251,146,60,0.45)', 'rgba(99,102,241,0.45)'],
        borderRadius: 4, borderSkipped: false
      }]
    },
    options: { responsive: true, indexAxis: 'y',
      plugins: { legend: { display: false }, tooltip: tooltipPlugin },
      scales: { x: Object.assign({}, gY), y: gX } }
  });

  // Initial build with all-time view
  buildCharts(allData, 0);
  updateMetrics(allData, 0);

  // Wire up time range selector
  window.setRange = function(days, el) {
    document.querySelectorAll('.range-opt').forEach(function(o) { o.classList.remove('active'); });
    el.classList.add('active');
    document.getElementById('rangeLabel').textContent = el.textContent.replace('\u2713', '').trim();
    document.getElementById('rangeMenu').classList.remove('open');
    buildCharts(allData, days);
    updateMetrics(allData, days);
  };

  // Wire up release annotation toggle
  window.toggleReleases = function() {
    showReleases = !showReleases;
    var btn = document.getElementById('releaseToggle');
    if (btn) { btn.classList.toggle('active-toggle', showReleases); }
    buildCharts(allData, currentDays);
  };
  // Set initial active state
  var initBtn = document.getElementById('releaseToggle');
  if (initBtn) { initBtn.classList.toggle('active-toggle', showReleases); }
}
